# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pablo Selín - comics, dibujos
email: pabloselin@gmail.com
instagram: donhilo
description: > # this means to ignore newlines until "baseurl:"
  Cómics y dibujos de Pablo Selín Carrasco Armijo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pablosel.in" # the base hostname & protocol for your site
collections:
 comics:
   output: true
   values:
    layout: comic
 drawings:
    output: true
    values:
      layout: drawing
# Build settings
markdown: kramdown
