# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: XX_XX
email: pabloselin@gmail.com
instagram: donhilo
description: > # this means to ignore newlines until "baseurl:"
  ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pablosel.in" # the base hostname & protocol for your site
collections:
 comics:
  output: true
  values:
   layout: comic
 drawings:
   output: true
   values:
    layout: drawing
 works:
  output: true
  values:
   layout: work
 zooms:
  output: true
  values: 
   layout: zoom
# Build settings
markdown: kramdown
